Print descriptive error message if test file does not exist
Added verification that test file or directory exists for the command:
run_tests.sh -t <test file>

If a test file (or directory) does not exist, run_tests.sh prints error message:
ERROR: File or directory <test file> not found
and exits with status 1

Change-Id: Ia0b11efe434daf7f040943ea8622bad496074563
Closes-Bug: #1397916