Bugfix for verify_networks_resp with incomplete data
verify_networks_resp fails with
UnboundLocalError: local variable 'received_network' referenced before assignment
if network data on first node is empty, if it is empty on second
received_network of previous node will be used..

Use data from cached_network cause received_network should be mirror of cached_networki
but it isn't in case of errors

Change-Id: I96e7e58e41a9699c5c41d78e181d499a9ea9f1b9