Plugins, do not fail if "attributes" is None
If plugin developer has the next environment_config.yaml

    attributes:

Nailgun fails with Exception.

    AttributeError: 'NoneType' object has no attribute 'setdefault'

Change-Id: I8f4c18b1e102e2b90335c5ba33a393c11c4168c8
Related-bug: #1396491